コードの微修正とrequirements.txtの追加
noir55/japanese_llm_simple_webui pull request #1
Opened 2023-08-07 13:24 UTC by hangingman

2023-08-07 13:33 UTC, hangingman commented
@noir55 修正のためPRを送ります
ご確認をお願いします

2023-08-12 02:20 UTC, noir55 approved these changes
原因調査と修正ありがとうございます。この修正は取り込ませていただきたいです。

2023-08-12 02:23 UTC, noir55 requested changes
Llama 2ベースのモデルだと4.31以降が必要など、使用するモデルによって必要となるTransformersのバージョンが異なるようなので、requirements.txtの追加は見送らせてください。

2023-08-12 02:32 UTC, noir55 commented
GitやGitHubの操作に慣れておらず、調べながらのため、期待されている対応ができていなかったらすみません。

2023-08-12 09:26 UTC, hangingman commented
@noir55 
>requirements.txtの追加は見送らせてください。

承知しました, requirements.txtは削除のcommitを入れておきます
あと、PRコメントには書いていませんでしたが.gitignoreも追加しています（リポジトリ管理不要なファイルをcommitするのを防ぐものです）

2023-08-14 14:07 UTC, merged

2023-08-14 14:10 UTC, noir55 commented
追加の修正ありがとうございます。マージさせていただきました。